config/routes.rb
Rails.application.routes.draw do
  # root to: '/dashboard'
  #
  # get '/dashboard', to: 'dashboards#show'

  resources  :songs
  resources :users, only: [:new, :create, :show]

  get '/login', to: "sessions#new"

  post '/login', to: "sessions#create"

  delete '/logout', to: "sessions#destroy"


end

app/models/song.rb
class Song < ActiveRecord::Base
  validates :title, presence: true, uniqueness: {scope: :artist}
  validates :artist, presence: true


  belongs_to :user

end

app/models/user.rb
class User < ActiveRecord::Base

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :username, presence: true


  has_secure_password
  has_many :songs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController


  def new

  end

  def create
    user = User.find_by(username: params[:session][:username])
    if user && user.authenticate(params[:session][:password])

      session[:user_id] = user.id

      redirect_to user
    else
      flash[:error] = "Invalid Credentials!"
      render :new
    end
  end

  def destroy
    session.clear
    flash[:notice] = "You have been logged out!"
    redirect_to login_path
  end

end

app/controllers/songs_controller.rb
class SongsController < ApplicationController

  def index
    session[:hit_counter] ||= 0
    session[:hit_counter] += 1
    @songs = Song.all
  end

  def show
    @song = Song.find(params[:id])
  end

  def create
    @song = Song.new(song_params)
    if @song.save
      flash[:notice] = "Song saved to your songs"
      redirect_to current_user
    else
      flash[:save_error] = @song.errors.full_messages.join(", ")
      render :new
    end
  end

  def new
    @song = Song.new(user_id: params[:user_id])
  end

  def edit
    @song = Song.find(params[:id])
  end

  def update
    @song = Song.find(params[:id])
    if @song.update(song_params)
      redirect_to song_path(@song)
    else
      render :edit
    end
  end

  def destroy
    @song = Song.find(params[:id])
    @song.destroy
    redirect_to songs_path
  end

  private

  def song_params
    params.require(:song).permit(:title, :artist, :user_id)
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to @user
    else
      flash[:errors] = @user.errors.full_messages.join(", ")
      render :new
    end
  end

  def show
  end

  private

  def user_params
    params.require(:user).permit(
    :first_name,
    :last_name,
    :username,
    :password,
    :password_confirmation
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyJams</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <header>
    <% if current_user %>
    <p><%= link_to "Logout", logout_path, method: :delete %></p>
    <% else %>
    <p><%= link_to "Login", login_path %> or <%= link_to "Create Account", new_user_path %>
    <%end %>
  </header>

  <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    <% end %>
    <%= yield %>



</body>
</html>

app/views/songs/_song_form.html.erb
<%= form_for(@song) do |f| %>
<%= f.text_field :title, placeholder: "Title" %>
<%= f.text_field :artist, placeholder: "Artist" %>
<%= f.hidden_field :user_id %>
<%= f.submit "Add that Jam!" %>
<% end %>

app/views/songs/edit.html.erb
<%= render partial: 'song_form' %>

app/views/songs/index.html.erb
<%= link_to "Create a new song!", new_song_path %>


<h1>My Jams</h1>

<h4> Page visited <%= session[:hit_counter] %> times.</h4>

<h3>Your Songs are:</h3>
<h5>click on song to go to song information</h5>
<ol>
  <% @songs.each do |song| %>

  <li><%= link_to song.title, song_path(song) %>
    by: <%= song.artist %></li>
  <% end %>
</ol>

app/views/songs/new.html.erb
  <%= render partial: 'song_form' %>

app/views/songs/show.html.erb
<h1><%= @song.title %></h1>
<h4>By: <%= @song.artist %></h4>
<%= link_to 'Edit this song.', edit_song_path(@song) %>
<%= link_to 'Delete', song_path(@song), method: :delete %>

app/views/users/new.html.erb
<%= form_for(@user) do |f| %>
<%= f.label :first_name %>
<%= f.text_field :first_name %>

<%= f.label :last_name %>
<%= f.text_field :last_name %>

<%= f.label :username %>
<%= f.text_field :username %>

<%= f.label :password %>
<%= f.password_field :password %>

<%= f.label :password_confirmation %>
<%= f.password_field :password_confirmation %>

<%= f.submit "Create User" %>

<% end %>

app/views/users/show.html.erb
<h1>Welcome <%= current_user.username %>!</h1>

<h3>Your Jams!</h3>
<h5><%= link_to "Add Jam", new_song_path(user_id: current_user.id) %></h5>

<table>
    <% current_user.songs.each do |song| %>
  <tr>
    <td>Song Title</td>
    <td>Artist</td>
  </tr>
  <tr>
    <td><%= song.title %></td>
    <td><%= song.artist %></td>
  </tr>
    <% end %>

</table>